# Generated by Django 4.2.1 on 2023-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_library', '0002_viewstuff_delete_addstuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=1000, verbose_name='promo')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
            ],
        ),
    ]
